### ISSUE TITLE
KeyError: 'deviceid'

### ISSUE THREAD

**Issue by DiegoGuisande** [aklyuk/zabbix-huawei-storages#5]
When execute:
./huawei_get_state.py --api_ip=xxx.xxx.xxx.xxx --api_port=8088 --api_user=username --api_password='password' --storage_name="storage_name_in_zabbix" --discovery

With de correct parameters, return the next error of de diviceid:
Traceback (most recent call last):
  File "./huawei_get_state.py", line 274, in <module>
    main()
  File "./huawei_get_state.py", line 263, in main
    result_discovery = discovering_resources(arguments.api_user, arguments.api_password, arguments.api_ip, arguments.api_port, arguments.storage_name, list_resources)
  File "./huawei_get_state.py", line 102, in discovering_resources
    device_id = api_connection[0]['data']['deviceid']
KeyError: 'deviceid'

Can you help me? Thanks.

**Comment by proffust** [comment]
Check error by curl
curl -k -X POST -d '{"scope":0,"username":"monitoring","password":""}' -H "Connection:keep-alive" -H "Content-Type:application/json" -H "Accept:application/json"  https://addr:8088/deviceManager/rest/xxxxx/sessions
